# <!-- rdoc-file=lib/rubygems/name_tuple.rb -->
# Represents a gem of name +name+ at +version+ of +platform+. These
# wrap the data returned from the indexes.
#
class Gem::NameTuple
  include Comparable

  @name: untyped

  @version: untyped

  @platform: untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - new(name, version, platform="ruby")
  # -->
  #
  def initialize: (untyped name, untyped version, ?untyped platform) -> void

  attr_reader name: untyped

  attr_reader version: untyped

  attr_reader platform: untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - from_list(list)
  # -->
  # Turn an array of [name, version, platform] into an array of
  # NameTuple objects.
  #
  def self.from_list: (untyped list) -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - to_basic(list)
  # -->
  # Turn an array of NameTuple objects back into an array of
  # [name, version, platform] tuples.
  #
  def self.to_basic: (untyped list) -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - null()
  # -->
  # A null NameTuple, ie name=nil, version=0
  #
  def self.null: () -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - full_name()
  # -->
  # Returns the full name (name-version) of this Gem.  Platform information is
  # included if it is not the default Ruby platform.  This mimics the behavior
  # of Gem::Specification#full_name.
  #
  def full_name: () -> ::String

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - match_platform?()
  # -->
  # Indicate if this NameTuple matches the current platform.
  #
  def match_platform?: () -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - prerelease?()
  # -->
  # Indicate if this NameTuple is for a prerelease version.
  #
  def prerelease?: () -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - spec_name()
  # -->
  # Return the name that the gemspec file would be
  #
  def spec_name: () -> ::String

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - to_a()
  # -->
  # Convert back to the [name, version, platform] tuple
  #
  def to_a: () -> untyped

  def inspect: () -> untyped

  alias to_s inspect

  def <=>: (untyped other) -> untyped

  # <!--
  #   rdoc-file=lib/rubygems/name_tuple.rb
  #   - ==(other)
  # -->
  # Compare with +other+. Supports another NameTuple or an Array
  # in the [name, version, platform] format.
  #
  def ==: (untyped other) -> untyped

  alias eql? ==

  def hash: () -> untyped
end
