name: Plugin Backwards Compatibility Tests

on:
  push:
    branches: [ master, '2025-04-28' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  typecheck_with_plugins:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: yq
        version: 1.0
    - name: Install gems
      run: |
        echo 'gem "solargraph-rails"' > .Gemfile
        echo 'gem "solargraph-rspec"' >> .Gemfile
        bundle install
    - name: Configure to use plugins
      run: |
        bundle exec solargraph config
        yq -yi '.plugins += ["solargraph-rails"]' .solargraph.yml
        yq -yi '.plugins += ["solargraph-rspec"]' .solargraph.yml
    - name: Install gem types
      run: bundle exec rbs collection install
    - name: Ensure typechecking still works
      run: bundle exec solargraph typecheck --level typed
    - name: Ensure specs still run
      run: bundle exec rake spec

  run_solargraph_rspec_specs:
    # check out solargraph-rspec as well as this project, and point the former to use the latter as a local gem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone https://github.com/lekemula/solargraph-rspec/
      run: |
       cd ..
       git clone https://github.com/lekemula/solargraph-rspec.git
       cd solargraph-rspec
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: false
    - name: Install gems
      run: |
       cd ../solargraph-rspec
       echo "gem 'solargraph', path: '../solargraph'" >> Gemfile
       bundle install
    - name: Run specs
      run: |
        cd ../solargraph-rspec
        bundle exec rake spec

  run_solargraph_rails_specs:
    # check out solargraph-rails as well as this project, and point the former to use the latter as a local gem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone https://github.com/iftheshoefritz/solargraph-rails/
      run: |
       cd ..
       # TODO:  Replace with main branch of iftheshoefritz/solargraph-rails once fixes are merged
       git clone -b 2025-05-07 https://github.com/apiology/solargraph-rails.git
       cd solargraph-rails
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # solargraph-rails supports Ruby 3.1+
        ruby-version: '3.1'
        bundler-cache: false
        # specified in Gemfile
        bundler: 2.3
    - name: Install gems
      run: |
       cd ../solargraph-rails
       cd spec/rails7
       echo "gem 'solargraph', path: '../../../solargraph'" >> Gemfile
       bundle install
       bundle exec rbs collection init
       bundle exec rbs collection install
       cd ../../
       echo "gem 'solargraph', path: '../solargraph'" >> Gemfile
       bundle install
       bundle exec rbs collection init
       bundle exec rbs collection install
    - name: Run specs
      run: |
        cd ../solargraph-rails
        bundle exec rake spec
